import Head from 'next/head'
import Header from '../components/header';
import Twitter from '../components/twitter';
import GitHub from '../components/github';
import { useState } from 'react';
import useInterval from 'use-interval';
import Link from 'next/link';

const Home = () => {
  const [displayedMessage, setDisplayedMessage] = useState('');
  const [messageTimer, setMessageTimer] = useState(0);
  const [messageColor, setMessageColor] = useState('yellow');
  const welcomeMessages = [
    '404 NOT FOUND',
    'ページが見つかりません...',
    'Sorry! Page Not Found...',

  ]
  const messageColors = ['yellow', 'pink', 'green', 'sky', 'red', 'gray', 'blue', 'indigo', 'purple']
  const messageBuffer = 30;
  const messagePatterns = welcomeMessages.map(msg => {
    const patterns: string[] = Array(msg.length + messageBuffer).fill('');
    return patterns.map((p, i) => msg.slice(0, i + 1));
  }).flat();

  useInterval(() => {
    setMessageTimer(messageTimer + 1);
    setDisplayedMessage(messagePatterns[messageTimer % messagePatterns.length]);
  }, 120);

  useInterval(() => {
    setMessageColor(messageColors[(messageTimer) % messageColors.length])
  }, 7000);

  return (
    <div>
      <Head>
        <title>TaigaOzawa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <main className="bg-gray-50 min-h-screen">
          <div className="flex justify-center">
            <div className="mt-36 text-xl sm:text-4xl font-bold font-montserrat">
              <div className={`px-3 border-b-4 border-${messageColor}-400 transition duration-1000`}>
                {displayedMessage}
              </div>
            </div>
          </div>

          <div className="text-sm sm:text-base px-3 flex flex-col items-center mt-5">
            <div>ご指定のページは見つかりませんでした。ページが存在しないか、移動した可能性があります。</div>
            <div>The requested URL was not found. The page may no longer exist or may be moved.</div>
          </div>

          <div className="flex justify-center mt-12">
            <Link href="/" passHref>
              <div className="px-2 pt-2 pb-1.5 rounded bg-yellow-300 hover:bg-yellow-400 transition duration-500 cursor-pointer">
                <span className="font-bold">
                  トップ&nbsp;
                </span>
                Top&nbsp;&nbsp;→
              </div>
            </Link>
          </div>

        </main>
        <footer>
          <div className="flex justify-center bg-gray-50 pb-5 w-screen text-sm text-gray-700">
            ©️2021 Taiga Ozawa. All rights reserved.
          </div>
        </footer>
      </div>
    </div>
  )
};

export default Home;
