import Head from 'next/head'
import Header from '../components/header';
import Twitter from '../components/twitter';
import GitHub from '../components/github';
import { useState } from 'react';
import useInterval from 'use-interval';
import Link from 'next/link';

const Home = () => {
  const [messageTimer, setMessageTimer] = useState(0);
  const [messageColor, setMessageColor] = useState('yellow');
  const messageColors = ['yellow', 'pink', 'green', 'sky', 'red', 'gray', 'blue', 'indigo', 'purple'];
  useInterval(() => {
    setMessageTimer(messageTimer + 1);
  }, 120);
  useInterval(() => {
    setMessageColor(messageColors[(messageTimer) % messageColors.length])
  }, 7000);

  return (
    <div>
      <Head>
        <title>TaigaOzawa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <main className="bg-gray-50 min-h-screen">
          <div className="flex justify-center">
            <div className="mt-24 text-lg sm:text-2xl font-bold font-montserrat">
              <div className={`text-center px-5 border-${messageColor}-400 border rounded pt-3 pb-2 transition text-gray-1000 duration-1000`}>
                <span>ノート・ブログ</span>&nbsp;<span>Notes & Blog</span>
              </div>
            </div>
          </div>

          <div className="flex justify-center mt-12">まだ投稿はありません...</div>
          <div className={`flex justify-center font-bold font-montserrat`}><div className={`px-3 border-${messageColor}-400 border-b-4 transition duration-1000`}>WORK IN PROGRESS...</div></div>
        </main>
        <footer>
          <div className="flex justify-center bg-gray-50 pb-5 w-screen text-sm text-gray-700">
            ©️2021 Taiga Ozawa. All rights reserved.
          </div>
        </footer>
      </div>
    </div>
  )
};

export default Home;
