import Head from 'next/head'
import Header from '../components/header';
import LangDropdown from '../components/langDropdown';
import { useState } from 'react';
import useInterval from 'use-interval';
import Link from 'next/link';

const Profile = () => {
  const [lang, setLang] = useState('ja');

  const [displayedBasicInfoTitle, setDisplayedBasicInfoTitle] = useState('');
  const [displayedBiographyTitle, setDisplayedBiographyTitle] = useState('');
  const [displayedSkillsTitle, setDisplayedSkillsTitle] = useState('');
  const [messageTimer, setMessageTimer] = useState(0);
  const [messageColor, setMessageColor] = useState('yellow');
  const basicInfoTitles = [
    '基本情報',
    'Basic Information'
  ]
  const biographyTitles = [
    '経歴',
    'Biography'
  ]
  const skillsTitles = [
    'スキル・資格',
    'Skills & Qualification'
  ]
  const messageColors = ['yellow', 'pink', 'green', 'sky', 'red', 'gray', 'blue', 'indigo', 'purple']
  const messageBuffer = 30;
  const basicInfoPatterns = basicInfoTitles.map(msg => {
    const patterns: string[] = Array(msg.length + messageBuffer).fill('');
    return patterns.map((p, i) => msg.slice(0, i + 1));
  }).flat();
  const biographyPatterns = biographyTitles.map(msg => {
    const patterns: string[] = Array(msg.length + messageBuffer).fill('');
    return patterns.map((p, i) => msg.slice(0, i + 1));
  }).flat();
  const skillsPatterns = skillsTitles.map(msg => {
    const patterns: string[] = Array(msg.length + messageBuffer).fill('');
    return patterns.map((p, i) => msg.slice(0, i + 1));
  }).flat();

  useInterval(() => {
    setMessageTimer(messageTimer + 1);
    setDisplayedBasicInfoTitle(basicInfoPatterns[messageTimer % basicInfoPatterns.length]);
    setDisplayedBiographyTitle(biographyPatterns[messageTimer % biographyPatterns.length]);
    setDisplayedSkillsTitle(skillsPatterns[messageTimer % skillsPatterns.length]);
  }, 120);

  useInterval(() => {
    setMessageColor(messageColors[(messageTimer) % messageColors.length])
  }, 7000);

  return (
    <div>
      <Head>
        <title>TaigaOzawa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <main className="bg-gray-50 min-h-screen">

          <div className="fixed w-screen mt-16">
            <div className="flex justify-center">
              <div className="w-screen max-w-7xl px-3 flex justify-end">
                <LangDropdown lang={lang} setLang={setLang} />
              </div>
            </div>
          </div>

          <div className="flex justify-center">
            <div className="mt-24 text-2xl font-bold font-montserrat">
              <div className={`px-3 border-b-4 border-${messageColor}-400 transition duration-1000`}>
                {displayedBasicInfoTitle}
              </div>
            </div>
          </div>

          {lang === 'ja' ?
            <div>日本語</div>
            :
            <div>English</div>
          }

          <div className="flex justify-center">
            <div className="mt-24 text-2xl font-bold font-montserrat">
              <div className={`px-3 border-b-4 border-${messageColor}-400 transition duration-1000`}>
                {displayedBiographyTitle}
              </div>
            </div>
          </div>

          <div className="flex justify-center">
            <div className="mt-24 text-2xl font-bold font-montserrat">
              <div className={`px-3 border-b-4 border-${messageColor}-400 transition duration-1000`}>
                {displayedSkillsTitle}
              </div>
            </div>
          </div>
        </main>
        <footer>
          <div className="flex justify-center bg-gray-50 pb-5 w-screen text-sm text-gray-700">
            ©️2021 Taiga Ozawa. All rights reserved.
          </div>
        </footer>
      </div>
    </div>
  )
};

export default Profile;
